s2an/little-shop-7

- Procfile
Adding Procfile for Heroku deployment (co-authored by all group members)
> Procfile for Heroku Deployment

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
Gems and setup somehow got deleted; reinitializing (co-authored by whole group)
> 50 add all pre approved gems take two

- Gemfile.lock
- app/models/customer.rb
- app/models/invoice.rb
- app/models/invoice_item.rb
- app/models/item.rb
- app/models/merchant.rb
- app/models/transaction.rb
- lib/tasks/csv_load.rake
- spec/models/customer_spec.rb
- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/item_spec.rb
- spec/models/merchant_spec.rb
- spec/models/transaction_spec.rb
- spec/rails_helper.rb
Meg and Dylan helped troubleshoot the primary key trouble.
> feat: Create rake tasks and primary key reset

- Gemfile.lock
- app/models/customer.rb
- app/models/invoice.rb
- app/models/invoice_item.rb
- app/models/item.rb
- app/models/merchant.rb
- app/models/transaction.rb
- spec/models/customer_spec.rb
- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/item_spec.rb
- spec/models/merchant_spec.rb
- spec/models/transaction_spec.rb
Added associations and tests to models
> Add associations to models

- Gemfile.lock
- app/models/customer.rb
- app/models/invoice.rb
- app/models/invoice_item.rb
- app/models/item.rb
- app/models/merchant.rb
- app/models/transaction.rb
- spec/models/customer_spec.rb
- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/item_spec.rb
- spec/models/merchant_spec.rb
- spec/models/transaction_spec.rb
Added enums and enum tests for:
- result on transactions table
- status on invoices table
- status on invoice_items table
> 8 research and implement enums

- spec/dashboard/index_spec.rb
- spec/factories/item.rb
- spec/factories/transaction.rb
Add associations in Fakerbot to create models.
> 57 finalize faker and factory bot testing and functionality

- app/controllers/dashboard_controller.rb
- app/views/dashboard/index.html.erb
- app/views/merchants/dashboard/show.html.erb
- config/routes.rb
- spec/features/dashboard/index_spec.rb
- spec/features/merchant/dashboard/show_spec.rb
**As a merchant,
When I visit my merchant dashboard (/merchants/:merchant_id/dashboard)
Then I see the name of my merchant**
This was tricky to implement given "dashboard" is not a restful route. However, I _think_ I've produced a restful implementation by giving "dashboard" its own controller, view, and test.
> 9 us 1 merchant dashboard

- .vscode/launch.json
- app/controllers/admin/merchants_controller.rb
- app/views/admin/merchants/index.html.erb
- config/routes.rb
- spec/features/admin/merchants/index_spec.rb
Added Admin Merchant Index Page
> 33 us 24 admin merchants index

- app/models/invoice.rb
- app/views/admin/invoices/show.html.erb
- config/routes.rb
- spec/features/admin/invoices/index_spec.rb
Completed the User Story.
Customer's First and Last Names can probably be concatenated, but I left them in separate fields for now.
Added a date formatter to the model...not sure if that is necessary, or can remain in the view.
Noticed that doing invoice = create(:invoice) also creates the associated customer! You don't need to declare customer = create(:invoice).
Factory bot is even better than I realized!
> 42 us 33 admin invoice show page

- app/views/admin/dashboard/index.html.erb
- config/routes.rb
- spec/features/admin/dashboard/index_spec.rb
Added links for the Admin Merchants and Admin Invoice on the Admin Dashboard page
> 29 us 20 admin dashboard links

- app/views/admin/invoices/show.html.erb
- spec/factories/invoice_item.rb
- spec/factories_spec.rb
- spec/features/admin/dashboard/index_spec.rb
- spec/features/admin/invoices/index_spec.rb
- spec/features/admin/invoices/show_spec.rb
- spec/features/dashboard/index_spec.rb
- spec/features/merchants/invoices_spec.rb
- spec/models/invoice_spec.rb
- Moves User Story 33's show test out of index_spec
- Adds a model test for User Story 33 (format_created_at)
- Adds a factory bot for invoice_items
- Adds a test for factory bot
- Completes User Story 34
- Didn't touch routes.rb, so hopefully there are no conflicts! 🤞
> 43 us 34 admin invoice show page invoice item information

- app/models/invoice.rb
- app/views/admin/invoices/show.html.erb
- spec/factories/invoice_item.rb
- spec/features/admin/invoices/show_spec.rb
- spec/models/invoice_spec.rb
Completed User Story 35
Oddities:
- Small edit remove '$' from show.html.erb line 6
- Update factory bot to take on the item's unit_price, instead of generating a new one
> 44 us 35 admin invoice show page total revenue

- app/controllers/admin/merchants_controller.rb
- app/models/merchant.rb
- app/views/admin/merchants/edit.html.erb
- app/views/admin/merchants/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/admin/merchants/edit_spec.rb
- spec/models/merchant_spec.rb
User Story 26 Added. Please review
> 35 us 26 admin merchant update

- app/models/merchant.rb
- app/views/dashboard/index.html.erb
- spec/features/dashboard/index_spec.rb
- spec/helper_methods.rb
- spec/models/customer_spec.rb
- spec/models/merchant_spec.rb
- spec/rails_helper.rb
This pull request adds the merchant model method `top_five_customers` and corresponding tests. This method can be run on any instance of a merchant to return a sorted array of that merchant's top five customers, as determined by their count of successful transactions with the merchant.
The merchant dashboard also displays these customers' full names and transaction counts.
As an aside, I added a `helper_methods.rb` to the spec folder to help organize testing data, as demonstrated in class today. Please feel free to add whatever you like to it, and use it as you see fit!
Finally, I re-organized my testing blocks to include user story labels as we discussed on slack.
> 12 us 3 merchant dashboard statistics favorite customers

- app/controllers/admin/invoices_controller.rb
- app/views/admin/invoices/show.html.erb
- config/routes.rb
- spec/features/admin/invoices/index_spec.rb
- spec/features/admin/invoices/show_spec.rb
NOT my best work, but functional. I hope to revisit later!
> 45 us 36 admin invoice show page update invoice status

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- config/routes.rb
- spec/features/dashboard/index_spec.rb
- spec/features/items/index_spec.rb
- Created items_controller.rb
- Added a route for /merchants/merchant_id/items
- Added a merchant items index view
- Added merchant items index view spec
- Removed an extra save_and_open_page so I could run bundle exec rspec without opening a new page every time
Note: this PR is meant to replace the original (https://github.com/s2an/little-shop-7/pull/76)
> 15 us 6 merchant items index page 2

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/show.html.erb
- config/routes.rb
- spec/features/dashboard/index_spec.rb
- spec/features/items/show_spec.rb
- spec/models/item_spec.rb
- Added a route for the merchant items show page
- Created a view for the merchant items show page
- Created merchant items show view spec
- Added a show action to the items controller
- Added a format_unit_price method to the item model
- Added a test for format_unit_price method in the item model spec
Note: this PR is meant to replace https://github.com/s2an/little-shop-7/pull/77
> 16 us 7 merchant items show page 2

- app/controllers/invoices_controller.rb
- app/models/invoice.rb
- app/models/invoice_item.rb
- app/models/merchant.rb
- app/views/invoices/show.html.erb
- spec/features/invoices/show_spec.rb
- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/merchant_spec.rb
- Added total_revenue_by_merchant method to invoice.rb model (User Story 17)
- Displayed total revenue on merchant invoice show page (User Story 17)
- Updated tests to create invoice items using the factory bot for consistency (User Story 14)
- Refactored some methods to be more RESTful (i.e. created item_ids method on merchant.rb model) (User Story 15)
- Debugged the items table on the merchant invoice show page and un-commented-out a test (User Story 16)
> 26 us 17 merchant invoice show page total revenue

- spec/models/merchant_spec.rb
Quick fix to a merge error, adding missing end
> Add missing end to merchant_spec.rb

- app/controllers/admin/dashboard_controller.rb
- app/models/invoice.rb
- app/views/admin/dashboard/index.html.erb
- spec/features/admin/dashboard/index_spec.rb
- spec/models/invoice_spec.rb
Finished the feature that displays only incomplete invoices in  a div section. It also has links to their respective show page in the invoices displayed.
> 31 us 22 admin dashboard incomplete invoices

- app/controllers/items_controller.rb
- app/models/merchant.rb
- app/views/items/index.html.erb
- config/routes.rb
- db/migrate/20240110064616_add_status_to_items.rb
- db/schema.rb
- spec/factories/item.rb
- spec/features/items/index_spec.rb
- spec/models/merchant_spec.rb
It's not my best work, but I think I got it working... I ended up creating two tables - one for enabled items and one for disabled. This was so that I could ensure the button I'm pressing is updating the correct item.
- Added update action to items controller
- Added two helper methods in the merchant model
- Added tests for each helper method in the merchant model spec
- Added two tables with enable/disable buttons to the items index view
- Added a test for the tables in the items index view spec
- Added a status column to the items table
- Updated the item factory so it will default item status to disabled
> 18 us 9 merchant item disableenable

- app/controllers/items_controller.rb
- app/views/items/edit.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- spec/features/items/show_spec.rb
- spec/models/merchant_spec.rb
- Added edit and update actions to the items controller
- Added an Update Item link to the items show page
- Added a test to the items show page spec
- Added an edit items view
- Added a route for editing items
- Allowed item routes to take in a param of :item_id instead of :id (before this change I was getting an error either in the terminal or in the server depending on if I had "item_id" or "id")
You'll notice I have some comments on lines 50-52 of the show_spec.rb. The test is not passing for some reason, even though when I test it out in the server I'm seeing the expected behavior - so I guess my test is written wrong? I'm not sure honestly, its strange. I'd love a second set of eyes!
> 17 us 8 merchant item update

- app/controllers/invoice_items_controller.rb
- app/views/invoices/show.html.erb
- config/routes.rb
- spec/features/admin/dashboard/index_spec.rb
- spec/features/dashboard/index_spec.rb
- spec/features/invoices/show_spec.rb
- added update action to invoice items controller
- added a status dropdown to the table on the merchants invoices show page
- added a route for updating invoice items
- added a test for the merchant invoices show spec
> 27 us 18 merchant invoice show page update item status 2

- app/controllers/items_controller.rb
- app/views/items/show.html.erb
- config/routes.rb
- spec/models/merchant_spec.rb
Fix routes for merchant item update, include missing end
> Fix routes for merchant item update, include missing end

- app/controllers/items_controller.rb
- spec/features/items/show_spec.rb
- added if statement to update action in items controller
- fixed test for user story 8 in items show spec
> debug update action in items controller

- app/views/layouts/application.html.erb
- Added some semblance of the header they are looking for in the wireframes
> Add headers to pages

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
- config/routes.rb
- db/schema.rb
- spec/features/items/index_spec.rb
Allows us to create New Items from the merchant items index page
> 20 us 11 merchant item create

- app/models/invoice.rb
- app/views/admin/dashboard/index.html.erb
- spec/factories/invoice.rb
- spec/features/admin/dashboard/index_spec.rb
- spec/models/invoice_spec.rb
- spec/models/merchant_spec.rb
User Story 23. Formatted the dates of invoice creation and displaying by oldest created first.
> 32 us 23 admin dashboard invoices sorted by least recent

- app/models/merchant.rb
- app/views/admin/merchants/index.html.erb
- db/schema.rb
- spec/features/admin/merchants/index_spec.rb
Only tests with one merchant for time sake.
> Complete User Story 28

- README.md
Added detailed description of the Little Esty Project to the readme file.
> added detailed description of the project
